import { Schema, model } from "mongoose";
import bcrypt from "bcrypt";
import { AdminRoles, IAdmin, IAccountStatus } from "../interface";
import { generatePassword } from "../functions";

interface IAdminDocument extends IAdmin {
    matchPasswords: (password: string) => boolean;
    changePassword: (password: string) => void;
    regeneratePassword: () => string;
    resetPassword: (password: string) => boolean;
    matchLastPasswords: (password: string) => boolean;
}

const adminSchema = new Schema<IAdminDocument>(
    {
        name: {
            type: String,
            required: true,
        },
        username: {
            type: String,
            required: true,
            unique: true,
            lowercase: true,
            trim: true,
            minlength: 3,
            maxlength: 15,
        },
        password: {
            type: String,
            required: true,
            select: false,
        },
        email: {
            type: String,
            required: true,
            unique: true,
            lowercase: true,
            trim: true,
        },
        role: {
            type: String,
            enum: AdminRoles,
            default: AdminRoles.ADMIN,
        },
        status: {
            type: String,
            required: true,
            enum: IAccountStatus,
            default: IAccountStatus.ACTIVE,
        },
    },
    { timestamps: true }
);

adminSchema.pre("save", async function (next) {
    if (this.isModified("password")) {
        const salt = await bcrypt.genSalt(10);
        this.password = await bcrypt.hash(this.password, salt);
    }
    // next();
});

adminSchema.methods.matchPasswords = async function (password: string) {
    return await bcrypt.compare(password, this.password);
};

adminSchema.methods.regeneratePassword = async function () {
    this.lastPassword = this.password;
    const newPassword = await generatePassword();
    this.generatePassword = true;
    this.password = newPassword;
    this.passwordChanged = true;
    this.passwordChangedAt = new Date();
    await this.save();
    return newPassword;
};

adminSchema.methods.resetPassword = async function (password: string) {
    if (this.resetPasswordAccess) {
        this.lastPassword = this.password;
        this.password = password;
        this.passwordChanged = true;
        this.passwordChangedAt = new Date();
        await this.save();
        return true;
    }
    return false;
};

adminSchema.methods.changePassword = async function async(password: string) {
    if (this.autoGeneratedPasswd) this.autoGeneratedPasswd = false;
    this.lastPassword = this.password;
    this.password = password;
    this.passwordChanged = true;
    this.passwordChangedAt = new Date();
    await this.save();
};

adminSchema.methods.matchLastPasswords = async function (password: string) {
    return await bcrypt.compare(password, this.lastPassword);
};

const Admin = model("admins", adminSchema);

export default Admin;
